# version: '3.8'

services:
  # Service pour la base de données MongoDB
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - devops-network
  server:
    build: ./server
    container_name: server
    ports:
      - "9000:9000"
    networks:
      - devops-network
    depends_on:
      - mongodb
    environment:
      # Le nom d'hôte 'mongodb' est résolu par Docker Compose
      - MONGO_URI=mongodb://mongodb:27017/mydatabase

  # Service pour le client frontend (React)
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - devops-network
    depends_on:
      - server

# Définition du réseau partagé
networks:
  devops-network:
    driver: bridge